[theme]
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200

[browser]
gatherUsageStats = false

[client]
showErrorDetails = true

[runner]
magicEnabled = false

# OpenAI API 설정
[openai]
OPENAI_API_KEY = "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"
OPENAI_API_USE_PW = "bslee73"
