[theme]
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200

[browser]
gatherUsageStats = false

[client]
showErrorDetails = true

[runner]
magicEnabled = false

# OpenAI API 설정
[openai]
OPENAI_API_KEY = "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"
OPENAI_API_USE_PW = "bslee73"
