[theme]
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200

[browser]
gatherUsageStats = false

[client]
showErrorDetails = true

[runner]
magicEnabled = false

[openai]
OPENAI_API_KEY = "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"
OPENAI_API_USE_PW = "bslee73"
